/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_StringAppendOperatorWithVariableDelimitor */

#ifndef _Included_org_rocksdb_StringAppendOperatorWithVariableDelimitor
#define _Included_org_rocksdb_StringAppendOperatorWithVariableDelimitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_StringAppendOperatorWithVariableDelimitor
 * Method:    newSharedStringAppendDelimOperator
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_StringAppendOperatorWithVariableDelimitor_newSharedStringAppendDelimOperator
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_rocksdb_StringAppendOperatorWithVariableDelimitor
 * Method:    disposeInternal
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_StringAppendOperatorWithVariableDelimitor_disposeInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
