/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_rocksdb_FlinkCompactionFilter */

#ifndef _Included_org_rocksdb_FlinkCompactionFilter
#define _Included_org_rocksdb_FlinkCompactionFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_rocksdb_FlinkCompactionFilter
 * Method:    createNewFlinkCompactionFilter0
 * Signature: (JLorg/rocksdb/FlinkCompactionFilter/TimeProvider;J)J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_FlinkCompactionFilter_createNewFlinkCompactionFilter0
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_rocksdb_FlinkCompactionFilter
 * Method:    createNewFlinkCompactionFilterConfigHolder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_rocksdb_FlinkCompactionFilter_createNewFlinkCompactionFilterConfigHolder
  (JNIEnv *, jclass);

/*
 * Class:     org_rocksdb_FlinkCompactionFilter
 * Method:    disposeFlinkCompactionFilterConfigHolder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_rocksdb_FlinkCompactionFilter_disposeFlinkCompactionFilterConfigHolder
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_rocksdb_FlinkCompactionFilter
 * Method:    configureFlinkCompactionFilter
 * Signature: (JIIJJILorg/rocksdb/FlinkCompactionFilter/ListElementFilterFactory;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_rocksdb_FlinkCompactionFilter_configureFlinkCompactionFilter
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jlong, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
